site_name: Distributaur
theme:
    name: material
    logo: assets/logo.png
    favicon: assets/favicon.ico
plugins:
- search
- autorefs
- mkdocstrings:
    enabled: true
    default_handler: python


    