site_name: Distributask
theme:
    name: material
    logo: assets/logo.png
    favicon: assets/favicon.ico
plugins:
- search
- autorefs
- mkdocstrings:
    enabled: true
    default_handler: python
nav:
    - Home: index.md
    - Getting Started: getting_started.md
    - More Information: more_info.md
    - Distributask Class: distributask.md


    