name: Lint and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    env:
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      REDIS_USER: ${{ secrets.REDIS_USER }}
      REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
      VAST_API_KEY: ${{ secrets.VAST_API_KEY }}
      HF_TOKEN: ${{ secrets.HF_TOKEN }}
      HF_REPO_ID: ${{ secrets.HF_REPO_ID }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install -r requirements.txt
    - name: Write package version
      run: echo ::set-output name=package_version::$(echo $GITHUB_REF | cut -d / -f 3) > version.txt
    - name: Running tests
      run: |
        pytest distributaur/tests/tests.py
